# Generated by Django 6.0.4 on 2026-04-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
