# Generated by Django 6.0.4 on 2026-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
